package service

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/anbanai/anban-creator/server/model"
)

var profileDimensionLabels = map[string]string{
	"identity":    "定位、主题边界和差异化",
	"style":       "语言、结构、视觉和表达风格",
	"audience":    "受众、需求和表达深度",
	"platforms":   "平台格式和适配规则",
	"preferences": "偏好、禁用项和合规红线",
	"memory":      "已验证经验和复盘结论",
}

// ProfileDimensionMarkdown is the stable, human-readable projection of one
// structured profile dimension. The database remains authoritative; this
// document is what Agents and Studio users read and edit.
func ProfileDimensionMarkdown(name string, dimension model.ProfileDimension) (string, error) {
	name = strings.TrimSpace(name)
	if _, ok := profileDimensionLabels[name]; !ok {
		return "", fmt.Errorf("unknown profile dimension %q", name)
	}
	if dimension.Content == nil {
		dimension.Content = map[string]any{}
	}
	content, err := json.MarshalIndent(dimension.Content, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal profile dimension %s: %w", name, err)
	}
	return fmt.Sprintf("# %s\n\n%s\n\n## 来源\n\n%s\n\n## 证据\n\n%s\n\n## 待补充\n\n%s\n",
		name,
		string(content),
		markdownList(dimension.Sources),
		markdownList(dimension.Evidence),
		markdownList(dimension.MissingFields)), nil
}

func markdownList(values []string) string {
	if len(values) == 0 {
		return "- 无"
	}
	lines := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			lines = append(lines, "- "+value)
		}
	}
	if len(lines) == 0 {
		return "- 无"
	}
	return strings.Join(lines, "\n")
}

// ProfileAgentsMarkdown is generated by the Server and is never an Agent
// output. Keeping this table server-owned prevents an Agent from changing the
// rules that govern how the profile is consumed.
func ProfileAgentsMarkdown() string {
	return `# AGENTS.md

## 项目画像引用

生成内容前必须读取以下六个项目画像文件：

| 引用路径 | 用途 |
| --- | --- |
| profile/identity.md | 定位、主题边界和差异化 |
| profile/style.md | 语言、结构、视觉和表达风格 |
| profile/audience.md | 受众、需求和表达深度 |
| profile/platforms.md | 平台格式和适配规则 |
| profile/preferences.md | 偏好、禁用项和合规红线，属于硬约束 |
| profile/memory.md | 已验证经验和复盘结论 |

## 读取规则

- 生成内容前必须读取六个文件。
- profile/preferences.md 的约束优先级最高。
- [待补充] 和 [推断待确认] 不能当作事实。
- 画像文件不属于 Agent 自动记忆，不要写入 .claude/agent-memory/*/MEMORY.md。
- 数据不足时保留缺失字段，不得编造结论。
`
}
