package config

import (
	"reflect"
	"strings"
	"testing"
	"time"

	"gopkg.in/yaml.v3"
)

func TestImageGenerationCapabilitiesYAMLContract(t *testing.T) {
	raw := `
default_capability: standard
capabilities:
  standard:
    alias: "Standard"
    description: "Daily image creation"
    min_tier: free
    billing_sku: image.standard
    provider: volcengine
    model: image-v1
    base_url: https://images.example.com
    api_key: secret
    timeout: 2m
    enabled: true
    quality_rank: 100
    features:
      supports_reference: true
      max_reference_images: 2
`
	var cfg ImageGenerationRoutesConfig
	if err := yaml.Unmarshal([]byte(raw), &cfg); err != nil {
		t.Fatalf("unmarshal new image capability config: %v", err)
	}

	value := reflect.ValueOf(cfg)
	defaultField := value.FieldByName("DefaultCapability")
	capabilitiesField := value.FieldByName("Capabilities")
	if !defaultField.IsValid() || defaultField.String() != "standard" {
		t.Fatalf("default_capability was not decoded: %#v", cfg)
	}
	if !capabilitiesField.IsValid() || capabilitiesField.Len() != 1 {
		t.Fatalf("capabilities were not decoded: %#v", cfg)
	}
	standard := capabilitiesField.MapIndex(reflect.ValueOf("standard"))
	if !standard.IsValid() {
		t.Fatalf("standard capability missing: %#v", cfg)
	}
	features := standard.FieldByName("Features")
	if !features.IsValid() || !features.FieldByName("SupportsReference").Bool() || features.FieldByName("MaxReferenceImages").Int() != 2 {
		t.Fatalf("features were not decoded: %#v", standard.Interface())
	}
}

func validCapabilityForConfigTest() ImageGenerationRouteConfig {
	return ImageGenerationRouteConfig{
		Provider: "volcengine", Model: "image-v1", BaseURL: "https://images.example.com", APIKey: "secret",
		Alias: "Standard", Description: "Daily image creation", MinTier: "free", BillingSKU: "image.standard",
		Timeout: 5 * time.Minute, Enabled: true, QualityRank: 100,
		Features: DesignerProviderCapabilities{DefaultSize: "1:1", SizePresets: []string{"1:1"}, MaxBatch: 1, OutputFormats: []string{"png"}},
	}
}

func TestImageCapabilityRuntimeAndTimeoutDefaults(t *testing.T) {
	cfg := Config{ModelRoutes: ModelRoutesConfig{ImageGeneration: ImageGenerationRoutesConfig{
		DefaultCapability: "standard", Capabilities: map[string]ImageGenerationRouteConfig{"standard": validCapabilityForConfigTest()},
	}}}
	route := cfg.ModelRoutes.ImageGeneration.Capabilities["standard"]
	route.Timeout = 0
	cfg.ModelRoutes.ImageGeneration.Capabilities["standard"] = route
	cfg.applyDefaults()
	runtime, ok := cfg.ImageAPIForCapability("")
	if !ok || runtime == nil {
		t.Fatalf("default capability runtime = %#v", runtime)
	}
	runtimeValue := reflect.ValueOf(*runtime)
	if runtimeValue.FieldByName("Cover").IsValid() || runtimeValue.FieldByName("Content").IsValid() {
		t.Fatalf("runtime adapter still exposes cover/content routes: %#v", runtime)
	}
	api := runtimeValue.FieldByName("API")
	if !api.IsValid() || api.IsNil() || api.Elem().FieldByName("TimeoutSec").Int() != 300 {
		t.Fatalf("default capability API = %#v", runtime)
	}
}

func TestValidateImageCapabilities(t *testing.T) {
	tests := []struct {
		name       string
		defaultKey string
		route      ImageGenerationRouteConfig
		want       string
	}{
		{name: "missing default", route: validCapabilityForConfigTest(), want: "default_capability is required"},
		{name: "unknown default", defaultKey: "missing", route: validCapabilityForConfigTest(), want: "must exist"},
		{name: "disabled default", defaultKey: "standard", route: func() ImageGenerationRouteConfig { r := validCapabilityForConfigTest(); r.Enabled = false; return r }(), want: "must be enabled"},
		{name: "paid default", defaultKey: "standard", route: func() ImageGenerationRouteConfig { r := validCapabilityForConfigTest(); r.MinTier = "pro"; return r }(), want: "default_capability must require free tier"},
		{name: "missing billing sku", defaultKey: "standard", route: func() ImageGenerationRouteConfig { r := validCapabilityForConfigTest(); r.BillingSKU = ""; return r }(), want: "billing_sku is required"},
		{name: "provider brand in alias", defaultKey: "standard", route: func() ImageGenerationRouteConfig {
			r := validCapabilityForConfigTest()
			r.Alias = "OpenAI Image"
			return r
		}(), want: "public text contains blocked brand"},
		{name: "model brand in description", defaultKey: "standard", route: func() ImageGenerationRouteConfig {
			r := validCapabilityForConfigTest()
			r.Description = "Generated by GPT"
			return r
		}(), want: "public text contains blocked brand"},
		{name: "missing features", defaultKey: "standard", route: func() ImageGenerationRouteConfig {
			r := validCapabilityForConfigTest()
			r.Features = DesignerProviderCapabilities{}
			return r
		}(), want: ".features invalid"},
		{name: "nonpositive quality rank", defaultKey: "standard", route: func() ImageGenerationRouteConfig { r := validCapabilityForConfigTest(); r.QualityRank = 0; return r }(), want: "quality_rank must be positive"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := baseKubernetesConfigForTest()
			cfg.ModelRoutes.ImageGeneration = ImageGenerationRoutesConfig{DefaultCapability: tt.defaultKey, Capabilities: map[string]ImageGenerationRouteConfig{"standard": tt.route}}
			err := cfg.Validate()
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("Validate() error = %v, want %q", err, tt.want)
			}
		})
	}
}

func TestValidateImageCapabilitiesRequiresFixedKeysAndAllowsCustomCapabilities(t *testing.T) {
	professional := validCapabilityForConfigTest()
	professional.Alias = "Professional"
	professional.Description = "Detailed image creation"
	professional.MinTier = "enterprise"
	professional.BillingSKU = "image.professional"
	custom := validCapabilityForConfigTest()
	custom.Alias = "Editorial"
	custom.Description = "Editorial illustration"
	custom.BillingSKU = "image.editorial"

	for _, tt := range []struct {
		name         string
		capabilities map[string]ImageGenerationRouteConfig
		want         string
	}{
		{
			name:         "missing standard",
			capabilities: map[string]ImageGenerationRouteConfig{"professional": professional},
			want:         "capabilities.standard is required",
		},
		{
			name:         "missing professional",
			capabilities: map[string]ImageGenerationRouteConfig{"standard": validCapabilityForConfigTest()},
			want:         "capabilities.professional is required",
		},
		{
			name: "custom capability remains allowed",
			capabilities: map[string]ImageGenerationRouteConfig{
				"standard": validCapabilityForConfigTest(), "professional": professional, "editorial": custom,
			},
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			cfg := baseKubernetesConfigForTest()
			cfg.ModelRoutes.ImageGeneration = ImageGenerationRoutesConfig{
				DefaultCapability: "standard",
				Capabilities:      tt.capabilities,
			}
			err := cfg.Validate()
			if tt.want == "" {
				if err != nil {
					t.Fatalf("Validate() error = %v", err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("Validate() error = %v, want %q", err, tt.want)
			}
		})
	}
}

func TestImageCapabilityYAMLRejectsUnknownAndMergeFields(t *testing.T) {
	for _, raw := range []string{
		"default_capability: standard\ncapabilities:\n  standard:\n    selection_keey: typo\n",
		"default_capability: standard\ncapabilities:\n  standard: &route\n    enabled: false\n  inherited:\n    <<: *route\n",
		"default_capability: standard\ncapabilities:\n  standard:\n    sizes:\n      article_cover: 16:9\n",
	} {
		var cfg ImageGenerationRoutesConfig
		if err := yaml.Unmarshal([]byte(raw), &cfg); err == nil {
			t.Fatalf("legacy/unknown image capability YAML accepted: %s", raw)
		}
	}
}

func TestImageGenerationCapabilitiesRejectLegacyYAML(t *testing.T) {
	tests := []struct {
		name string
		raw  string
		want string
	}{
		{name: "cover", raw: "cover:\n  provider: openai\n", want: "cover"},
		{name: "content", raw: "content:\n  provider: openai\n", want: "content"},
		{name: "designer", raw: "designer:\n  openai:\n    provider: openai\n", want: "designer"},
		{name: "selection key", raw: "default_capability: standard\ncapabilities:\n  standard:\n    selection_key: legacy\n", want: "selection_key"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var cfg ImageGenerationRoutesConfig
			err := yaml.Unmarshal([]byte(tt.raw), &cfg)
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("unmarshal error = %v, want rejection containing %q", err, tt.want)
			}
		})
	}
}
