package model

import "gorm.io/gorm"

// AutoMigrate creates or updates all database tables.
func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(
		&AnalyticsState{}, &AnalyticsContent{}, &AnalyticsObservation{}, &AnalyticsRawPayload{}, &AnalyticsBucket{}, &AnalyticsIdempotency{}, &AnalyticsRebuildJob{},
		&FeedbackJob{}, &FeedbackLease{}, &FeedbackInsight{}, &StrategySnapshot{}, &GenerationContext{},
		&User{},
		&LoginSession{},
		&Project{},
		&ProjectProfileState{},
		&ProjectProfileRevision{},
		&ProjectChannelConfig{},
		&Plan{},
		&PlanEntry{},
		&Task{},
		&WechatPublication{},
		&WechatProjectReconcileLease{},
		&WechatPublicationBinding{},
		&WechatPublicationAttempt{},
		&WechatAccountCapability{},
		&TaskExecution{},
		&TaskFile{},
		&TaskFileObjectCleanup{},
		&UploadSession{},
		&Asset{},
		&APIKey{},
		&Feedback{},
		&TaskFeedback{},
		&SeednotePostTracking{},
		&SeednoteMetricSnapshot{},
		&SeednoteImportBatch{},
		&SeednoteImportRow{},
		&SeednotePost{},
		&SeednotePostAlias{},
		&SeednoteMetricVersion{},
		&WechatArticleTracking{},
		&WechatMetricSnapshot{},
		&WechatAnalyticsImportBatch{},
		&WechatAnalyticsImportRow{},
		&WechatAnalyticsSnapshot{},
		&ChannelsVideoTracking{},
		&ChannelsMetricSnapshot{},
		&Template{},
		&ImageAnalysisJob{},
		&ViralAnalysis{},
		&PosterTask{},
		&TopicPool{},
		&TrendSnapshot{},
		&AgentFeedback{},
		&ContentMetadataReport{},
		&ContentTagAssignment{},
		&ContentTagVocabulary{},
		&IlinkBinding{},
		&IlinkNotification{},
		&BillingWalletAccount{},
		&BillingCreditLot{},
		&BillingWalletEntry{},
		&BillingCatalogVersion{},
		&BillingSKU{},
		&BillingSKUTierPrice{},
		&BillingQuote{},
		&BillingCharge{},
		&BillingChargeAllocation{},
		&BillingDebtAllocation{},
		&BillingSettlementOutbox{},
		&BillingReferralIssue{},
		&BillingProviderCostEvent{},
		&BillingExecutionCostStatus{},
		&BillingMarginFact{},
		&SearchOperation{},
	)
}
