import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertCircle, Check, CheckCircle2, Download, FileSpreadsheet, RefreshCw, Upload, X } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import PageHeader from '@/components/layout/PageHeader'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { api } from '@/lib/api'
import { uploadToOSS } from '@/lib/direct-upload'
import { queryKeys } from '@/lib/query-keys'
import type { Project } from '@/types'
import type { SeednoteImportRow, SeednoteMetricVersion } from '@/types/seednote-import'

const metrics = [
  ['exposure_count', '曝光', 'count'], ['view_count', '观看量', 'count'], ['cover_click_rate', '封面点击率', 'rate'],
  ['like_count', '点赞', 'count'], ['comment_count', '评论', 'count'], ['collect_count', '收藏', 'count'],
  ['follower_gain_count', '涨粉', 'count'], ['share_count', '分享', 'count'], ['avg_watch_duration', '人均观看时长', 'duration'], ['barrage_count', '弹幕', 'count'],
] as const
type MetricKey = typeof metrics[number][0]
type DatePreset = 'week' | 'month' | '7d' | '30d' | 'custom'
const defaultMetrics: MetricKey[] = ['view_count', 'like_count', 'comment_count', 'collect_count']
const metricColors: Record<MetricKey, string> = { exposure_count: '#f97316', view_count: '#2563eb', cover_click_rate: '#7c3aed', like_count: '#e11d48', comment_count: '#0891b2', collect_count: '#16a34a', follower_gain_count: '#9333ea', share_count: '#ca8a04', avg_watch_duration: '#475569', barrage_count: '#0f766e' }
function localDate(value: Date) { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit' }).format(value) }
function nextDate(value: string) { const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + 1); return date.toISOString().slice(0, 10) }
function shanghaiISOString(value: string) { return new Date(`${value}:00+08:00`).toISOString() }
function normalizeTitle(value: string) { return value.normalize('NFKC').trim().replace(/\s+/g, ' ') }
function samePublishTime(a?: string | null, b?: string | null) { return Boolean(a && b && new Date(a).getTime() === new Date(b).getTime()) }
function metricLabel(key: MetricKey) { return metrics.find(([value]) => value === key)?.[1] ?? key }
function metricKind(key: MetricKey) { return metrics.find(([value]) => value === key)?.[2] }
function metricNote(key: MetricKey) { return metricKind(key) === 'rate' || metricKind(key) === 'duration' ? '按有值帖子平均' : '按已确认帖子求和' }
function formatMetric(value: number | null | undefined, key: MetricKey) { if (value == null) return '-'; const kind = metricKind(key); if (kind === 'rate') return `${(value * 100).toFixed(2)}%`; if (kind === 'duration') return `${value.toFixed(1)} 秒`; return value.toLocaleString('zh-CN') }
function formatFileSize(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB` }
function statusLabel(status: string) { return ({ processing: '解析中', needs_review: '待确认', completed: '已完成', failed: '失败' } as Record<string, string>)[status] ?? status }
function latestDailyVersions(versions: SeednoteMetricVersion[]) { const latest = new Map<string, SeednoteMetricVersion>(); versions.forEach((version) => { const date = version.data_as_of_at.slice(0, 10); const current = latest.get(date); if (!current || new Date(version.imported_at).getTime() > new Date(current.imported_at).getTime()) latest.set(date, version) }); return [...latest.values()].sort((a, b) => a.data_as_of_at.localeCompare(b.data_as_of_at)) }
function rangeForPreset(preset: Exclude<DatePreset, 'custom'>, now = new Date()) { const to = localDate(now); const fromDate = new Date(`${to}T00:00:00Z`); if (preset === 'week') fromDate.setUTCDate(fromDate.getUTCDate() - ((fromDate.getUTCDay() + 6) % 7)); if (preset === 'month') fromDate.setUTCDate(1); if (preset === '7d') fromDate.setUTCDate(fromDate.getUTCDate() - 6); if (preset === '30d') fromDate.setUTCDate(fromDate.getUTCDate() - 29); return { from: fromDate.toISOString().slice(0, 10), to } }
function aggregateSeriesValue(series: Array<Partial<Record<MetricKey, number | null | undefined>>>, key: MetricKey) { const values = series.map((item) => item[key]).filter((value): value is number => typeof value === 'number'); if (!values.length) return null; return metricKind(key) === 'rate' || metricKind(key) === 'duration' ? values.reduce((sum, value) => sum + value, 0) / values.length : values.reduce((sum, value) => sum + value, 0) }

export default function SeednoteDataPage() {
  const queryClient = useQueryClient(); const [projectId, setProjectId] = useState(''); const [selectedBatch, setSelectedBatch] = useState<string | null>(null); const [selectedPost, setSelectedPost] = useState<string | null>(null); const [selectedMetrics, setSelectedMetrics] = useState<MetricKey[]>(defaultMetrics); const [stagedFile, setStagedFile] = useState<File | null>(null); const [fileError, setFileError] = useState(''); const [importOpen, setImportOpen] = useState(false); const [datePreset, setDatePreset] = useState<DatePreset>('30d'); const [asOf, setAsOf] = useState(() => `${localDate(new Date())}T23:59`); const initialRange = rangeForPreset('30d'); const [from, setFrom] = useState(initialRange.from); const [to, setTo] = useState(initialRange.to)
  const projectsQuery = useQuery({ queryKey: queryKeys.projects.list({ platform: 'seednote' }), queryFn: () => api.projects.list({ platform: 'seednote' }) }); const projects = (projectsQuery.data ?? []) as Project[]; const activeProjectId = projectId; const activeProject = projects.find((project) => project.id === activeProjectId); const overviewParams = { from: from || undefined, to: to ? nextDate(to) : undefined }
  const batchesQuery = useQuery({ queryKey: queryKeys.seednoteImport.batches(activeProjectId), queryFn: () => api.seednoteImport.listBatches(activeProjectId), enabled: Boolean(activeProjectId) }); const overviewQuery = useQuery({ queryKey: queryKeys.seednoteImport.overview(activeProjectId, overviewParams), queryFn: () => api.seednoteImport.overview(activeProjectId, overviewParams), enabled: Boolean(activeProjectId) }); const batchQuery = useQuery({ queryKey: queryKeys.seednoteImport.batch(activeProjectId, selectedBatch || ''), queryFn: () => api.seednoteImport.getBatch(activeProjectId, selectedBatch!), enabled: Boolean(activeProjectId && selectedBatch) }); const postsQuery = useQuery({ queryKey: queryKeys.seednoteImport.posts(activeProjectId), queryFn: () => api.seednoteImport.posts(activeProjectId, undefined, { limit: 1000 }), enabled: Boolean(activeProjectId) }); const postQuery = useQuery({ queryKey: queryKeys.seednoteImport.post(activeProjectId, selectedPost || '', overviewParams), queryFn: () => api.seednoteImport.post(activeProjectId, selectedPost!, overviewParams), enabled: Boolean(activeProjectId && selectedPost) })
  const importMutation = useMutation({ mutationFn: async (file: File) => { if (!activeProjectId) throw new Error('请先选择小红书账号'); const uploaded = await uploadToOSS({ purpose: 'seednote_analytics_import', file }); return api.seednoteImport.import(activeProjectId, { upload_id: uploaded.uploadSessionId, data_as_of_at: shanghaiISOString(asOf), timezone: 'Asia/Shanghai', client_file_modified_at: new Date(file.lastModified).toISOString() }) }, onSuccess: (result) => { setImportOpen(false); setStagedFile(null); setSelectedBatch(result.batch.id); queryClient.invalidateQueries({ queryKey: queryKeys.seednoteImport.batches(activeProjectId) }); queryClient.invalidateQueries({ queryKey: queryKeys.seednoteImport.overview(activeProjectId) }); queryClient.invalidateQueries({ queryKey: queryKeys.seednoteImport.posts(activeProjectId) }) } })
  const resolveMutation = useMutation({ mutationFn: (actions: Array<{ row_id: string; action: string; post_id?: string }>) => api.seednoteImport.resolve(activeProjectId, selectedBatch!, actions), onSuccess: () => { queryClient.invalidateQueries({ queryKey: queryKeys.seednoteImport.batch(activeProjectId, selectedBatch || '') }); queryClient.invalidateQueries({ queryKey: queryKeys.seednoteImport.overview(activeProjectId) }); queryClient.invalidateQueries({ queryKey: queryKeys.seednoteImport.posts(activeProjectId) }) } })
  const series = overviewQuery.data?.series ?? []; const posts = postsQuery.data?.items ?? []; const postSummaries = overviewQuery.data?.post_summaries ?? []; const reviewRows = (batchQuery.data?.rows ?? []).filter((row) => row.match_status === 'needs_review' || row.match_status === 'invalid'); const pendingRows = reviewRows.filter((row) => row.match_status === 'needs_review'); const invalidRows = reviewRows.filter((row) => row.match_status === 'invalid'); const chartData = useMemo(() => series.map((item) => ({ ...item, label: item.date.slice(5) })), [series]); const postVersions = useMemo(() => latestDailyVersions(postQuery.data?.versions ?? []), [postQuery.data?.versions]); const selectedPostSummary = postSummaries.find((post) => post.id === selectedPost); const stats = useMemo(() => [['exposure_count', '曝光'], ['view_count', '观看量'], ['like_count', '点赞'], ['comment_count', '评论'], ['collect_count', '收藏'], ['follower_gain_count', '涨粉']].map(([key, label]) => ({ key: key as MetricKey, label, value: aggregateSeriesValue(series, key as MetricKey) })), [series])
  function changeProject(nextProjectId: string) { setProjectId(nextProjectId); setSelectedBatch(null); setSelectedPost(null); setStagedFile(null); setFileError(''); setImportOpen(false) }
  function stageFile(file?: File) { setFileError(''); if (!file) return; if (!file.name.toLowerCase().endsWith('.xlsx')) { setStagedFile(null); setFileError('仅支持小红书官方导出的 .xlsx 文件'); return }; if (file.size > 20 * 1024 * 1024) { setStagedFile(null); setFileError('文件不能超过 20 MB'); return }; setStagedFile(file) }
  function applyPreset(preset: Exclude<DatePreset, 'custom'>) { const range = rangeForPreset(preset); setDatePreset(preset); setFrom(range.from); setTo(range.to) }
  function toggleMetric(nextMetric: MetricKey) { setSelectedMetrics((current) => current.includes(nextMetric) ? (current.length > 1 ? current.filter((metric) => metric !== nextMetric) : current) : current.length < 4 ? [...current, nextMetric] : current) }
  async function downloadBatch(batchId: string) { const result = await api.seednoteImport.file(activeProjectId, batchId); window.open(result.url, '_blank', 'noopener,noreferrer') }
  function exactCandidatesFor(row: SeednoteImportRow) { return posts.filter((post) => normalizeTitle(post.title) === normalizeTitle(row.title) && samePublishTime(post.first_published_at, row.first_published_at)) }

  return <div className="space-y-6">
    <PageHeader title="小红书数据" description="按周期查看账号和帖子表现，数据导入只在需要时进行。">{activeProjectId && <Button onClick={() => setImportOpen(true)}><Upload />导入数据</Button>}</PageHeader>
    <Card><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-end lg:justify-between"><label className="grid gap-2 text-sm" htmlFor="seednote-account"><span className="font-medium">小红书账号 <span className="text-destructive">*</span></span>{projectsQuery.isFetched ? <select id="seednote-account" aria-label="小红书账号" className="h-10 min-w-64 rounded-md border border-input bg-background px-3" value={projectId} disabled={importMutation.isPending} onChange={(event) => changeProject(event.target.value)}><option value="">请选择要查看的账号</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select> : <span className="flex h-10 items-center rounded-md border border-input px-3 text-muted-foreground">正在读取账号…</span>}</label>{activeProject ? <div className="flex items-center gap-2 text-sm text-muted-foreground"><CheckCircle2 className="h-4 w-4 text-primary" />当前查看：<span className="font-medium text-foreground">{activeProject.name}</span></div> : <p className="text-sm text-muted-foreground">请选择账号后查看数据看板</p>}</CardContent></Card>
    {activeProjectId && <><Card><CardContent className="flex flex-col gap-4 p-5 xl:flex-row xl:items-center xl:justify-between"><div><p className="text-sm font-medium">数据看板</p><p className="mt-1 text-xs text-muted-foreground">当前范围：{from} 至 {to}</p></div><div className="flex flex-wrap gap-2" aria-label="日期范围">{([['week', '本周'], ['month', '本月'], ['7d', '近 7 天'], ['30d', '近 30 天'], ['custom', '自定义']] as const).map(([value, label]) => <Button key={value} type="button" size="sm" variant={datePreset === value ? 'default' : 'outline'} onClick={() => value === 'custom' ? setDatePreset('custom') : applyPreset(value)}>{label}</Button>)}</div>{datePreset === 'custom' && <div className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs text-muted-foreground">开始日期<Input aria-label="开始日期" className="h-9 w-40" type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /></label><label className="grid gap-1 text-xs text-muted-foreground">结束日期<Input aria-label="结束日期" className="h-9 w-40" type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></label></div>}</CardContent></Card>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{stats.map((stat) => <Card key={stat.key}><CardContent className="p-4"><p className="text-sm text-muted-foreground">{stat.label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{formatMetric(stat.value, stat.key)}</p><p className="mt-1 text-xs text-muted-foreground">{metricNote(stat.key)}</p></CardContent></Card>)}</div>
      <Card><CardHeader className="gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle>账号趋势</CardTitle><p className="mt-1 text-xs text-muted-foreground">可同时查看最多 4 项指标</p></div><div className="flex flex-wrap gap-1.5" aria-label="趋势指标">{metrics.map(([key, label]) => <Button key={key} type="button" size="sm" variant={selectedMetrics.includes(key) ? 'secondary' : 'ghost'} aria-pressed={selectedMetrics.includes(key)} onClick={() => toggleMetric(key)}>{label}</Button>)}</div></CardHeader><CardContent><div className="h-80">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" className="stroke-border" /><XAxis dataKey="label" /><YAxis allowDecimals /><Tooltip formatter={(value, name) => [formatMetric(Number(value), name as MetricKey), metricLabel(name as MetricKey)]} />{selectedMetrics.map((key) => <Line key={key} type="monotone" dataKey={key} name={key} stroke={metricColors[key]} strokeWidth={2} dot={false} connectNulls />)}</LineChart></ResponsiveContainer> : <p className="py-24 text-center text-sm text-muted-foreground">暂无已确认数据，请先导入并完成匹配。</p>}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>帖子表现</CardTitle><p className="text-sm text-muted-foreground">按当前日期范围汇总，点击帖子查看详细趋势。</p></CardHeader><CardContent className="space-y-4"><div className="overflow-x-auto"><Table className="min-w-[720px]"><TableHeader><TableRow><TableHead>帖子</TableHead><TableHead>曝光</TableHead><TableHead>点赞</TableHead><TableHead>评论</TableHead><TableHead>收藏</TableHead><TableHead>涨粉</TableHead></TableRow></TableHeader><TableBody>{postSummaries.map((post) => <TableRow key={post.id} className={selectedPost === post.id ? 'bg-primary/5' : ''}><TableCell><button type="button" className="max-w-[320px] truncate text-left font-medium hover:text-primary" onClick={() => setSelectedPost(post.id)}>{post.title}</button><p className="mt-1 text-xs text-muted-foreground">{post.first_published_at ? new Date(post.first_published_at).toLocaleDateString('zh-CN') : '未提供发布时间'}</p></TableCell><TableCell>{formatMetric(post.exposure_count, 'exposure_count')}</TableCell><TableCell>{formatMetric(post.like_count, 'like_count')}</TableCell><TableCell>{formatMetric(post.comment_count, 'comment_count')}</TableCell><TableCell>{formatMetric(post.collect_count, 'collect_count')}</TableCell><TableCell>{formatMetric(post.follower_gain_count, 'follower_gain_count')}</TableCell></TableRow>)}</TableBody></Table></div>{!postSummaries.length && <p className="py-10 text-center text-sm text-muted-foreground">确认匹配后，帖子会显示在这里。</p>}{selectedPost && postQuery.data && <div className="border-t pt-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{selectedPostSummary?.title ?? postQuery.data.post.title}</p><p className="mt-1 text-xs text-muted-foreground">{metricLabel(selectedMetrics[0])} · {from} 至 {to}</p></div><Button type="button" variant="ghost" size="icon" aria-label="关闭帖子详情" onClick={() => setSelectedPost(null)}><X /></Button></div><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={postVersions.map((version) => ({ ...version, label: version.data_as_of_at.slice(0, 10) }))}><CartesianGrid strokeDasharray="3 3" className="stroke-border" /><XAxis dataKey="label" /><YAxis allowDecimals /><Tooltip formatter={(value) => formatMetric(Number(value), selectedMetrics[0])} /><Line type="monotone" dataKey={selectedMetrics[0]} stroke={metricColors[selectedMetrics[0]]} strokeWidth={2} dot={false} connectNulls /></LineChart></ResponsiveContainer></div></div>}</CardContent></Card>
      {selectedBatch && batchQuery.data && <>
        {invalidRows.length > 0 && <Alert variant="destructive"><AlertCircle /><AlertTitle>导入存在无法解析的行</AlertTitle><AlertDescription><p>以下 {invalidRows.length} 行未进入看板，请修正源文件后重新导入：</p><ul className="mt-2 list-disc pl-5">{invalidRows.map((row) => <li key={row.id}>第 {row.source_row} 行{row.parse_error ? `：${row.parse_error}` : ''}</li>)}</ul></AlertDescription></Alert>}
        {pendingRows.length > 0 ? <Card><CardHeader><CardTitle>待确认匹配 <span className="text-sm font-normal text-muted-foreground">{pendingRows.length} 条</span></CardTitle><p className="text-sm text-muted-foreground">只有系统无法唯一确认的帖子需要处理。</p></CardHeader><CardContent><div className="overflow-x-auto"><Table className="min-w-[900px]"><TableHeader><TableRow><TableHead>源行</TableHead><TableHead>标题</TableHead><TableHead>首次发布时间</TableHead><TableHead>处理</TableHead></TableRow></TableHeader><TableBody>{pendingRows.map((row) => { const candidates = exactCandidatesFor(row); return <TableRow key={row.id}><TableCell>{row.source_row}</TableCell><TableCell className="max-w-[300px] truncate" title={row.title}>{row.title}</TableCell><TableCell>{row.first_published_at ? new Date(row.first_published_at).toLocaleString('zh-CN') : '未提供'}</TableCell><TableCell><div className="flex flex-wrap gap-2">{candidates.map((post) => <Button key={post.id} size="sm" variant="outline" disabled={resolveMutation.isPending} onClick={() => resolveMutation.mutate([{ row_id: row.id, action: 'link_existing', post_id: post.id }])}><Check />关联「{post.title}」</Button>)}<Button size="sm" variant="outline" disabled={resolveMutation.isPending} onClick={() => resolveMutation.mutate([{ row_id: row.id, action: 'create_new' }])}>新建帖子</Button><Button size="sm" variant="ghost" disabled={resolveMutation.isPending} onClick={() => resolveMutation.mutate([{ row_id: row.id, action: 'skip' }])}>跳过</Button></div>{row.parse_error && <p className="mt-1 text-xs text-destructive">{row.parse_error}</p>}{!candidates.length && <p className="mt-1 text-xs text-muted-foreground">未找到唯一候选，请确认后新建或跳过。</p>}</TableCell></TableRow> })}</TableBody></Table></div></CardContent></Card> : invalidRows.length === 0 && <Alert><CheckCircle2 /><AlertTitle>导入完成</AlertTitle><AlertDescription>帖子已自动匹配，看板已刷新。</AlertDescription></Alert>}
      </>}
      <details className="rounded-xl border border-border bg-card px-4 py-3"><summary className="cursor-pointer list-none text-sm font-medium">历史导入 <span className="ml-1 text-muted-foreground">{batchesQuery.data?.total ?? 0}</span></summary><div className="mt-3 space-y-2">{(batchesQuery.data?.items ?? []).map((batch) => <div key={batch.id} className={`rounded-lg border p-3 text-sm ${selectedBatch === batch.id ? 'border-primary bg-primary/5' : 'border-border'}`}><div className="flex items-center justify-between gap-2"><button type="button" className="min-w-0 truncate text-left font-medium" onClick={() => setSelectedBatch(batch.id)}>{batch.file_name}</button><span className="text-xs text-muted-foreground">{statusLabel(batch.status)}</span></div><div className="mt-1 flex items-center justify-between gap-3 text-xs text-muted-foreground"><span>数据截至 {new Date(batch.data_as_of_at).toLocaleString('zh-CN')} · {batch.resolved_rows}/{batch.total_rows} 行已确认</span><Button variant="ghost" size="sm" className="h-7 px-2" title="下载原始文件" onClick={() => void downloadBatch(batch.id)}><Download className="mr-1 h-3.5 w-3.5" />下载</Button></div></div>)}{!batchesQuery.data?.items?.length && <p className="py-3 text-sm text-muted-foreground">还没有导入批次</p>}</div></details>{overviewQuery.isFetching && <div className="text-xs text-muted-foreground"><RefreshCw className="mr-1 inline h-3 w-3 animate-spin" />数据刷新中</div>}</>}
    {importMutation.error && <Alert variant="destructive"><AlertCircle /><AlertTitle>导入失败</AlertTitle><AlertDescription>{(importMutation.error as Error).message}</AlertDescription></Alert>}
    <Dialog open={importOpen} onOpenChange={(open) => !importMutation.isPending && setImportOpen(open)}><DialogContent className="sm:max-w-lg" closeButtonDisabled={importMutation.isPending}><DialogHeader><DialogTitle>导入数据</DialogTitle><DialogDescription>选择小红书官方 XLSX，系统会自动匹配帖子；只有有歧义的行需要你确认。</DialogDescription></DialogHeader><div className="space-y-4"><div className="rounded-lg bg-muted/60 p-3 text-sm"><span className="text-muted-foreground">导入账号：</span><span className="font-medium">{activeProject?.name ?? '-'}</span></div><label htmlFor="seednote-import-file" className="flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed bg-muted/20 px-5 text-center transition-colors hover:border-primary/50 hover:bg-muted/50"><FileSpreadsheet className="mb-3 h-8 w-8 text-primary" /><span className="sr-only">导入数据文件</span><span className="text-sm font-medium">选择小红书官方 XLSX</span><span className="mt-1 text-xs text-muted-foreground">仅支持 .xlsx，最大 20 MB</span><input id="seednote-import-file" className="sr-only" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" aria-label="导入数据文件" disabled={importMutation.isPending} onChange={(event) => { stageFile(event.target.files?.[0]); event.currentTarget.value = '' }} /></label>{stagedFile && <div className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="flex min-w-0 items-center gap-3"><FileSpreadsheet className="h-5 w-5 shrink-0 text-primary" /><div className="min-w-0"><p className="truncate text-sm font-medium">{stagedFile.name}</p><p className="text-xs text-muted-foreground">{formatFileSize(stagedFile.size)} · 尚未上传</p></div></div><Button type="button" variant="ghost" size="sm" onClick={() => setStagedFile(null)}>移除</Button></div>}{fileError && <p className="text-sm text-destructive"><AlertCircle className="mr-1 inline h-4 w-4" />{fileError}</p>}<label className="grid gap-2 text-sm" htmlFor="seednote-as-of"><span className="font-medium">数据截至时间</span><Input id="seednote-as-of" type="datetime-local" value={asOf} onChange={(event) => setAsOf(event.target.value)} /><span className="text-xs text-muted-foreground">默认使用今天 23:59。</span></label></div><DialogFooter><Button type="button" variant="outline" disabled={importMutation.isPending} onClick={() => setImportOpen(false)}>取消</Button><Button type="button" disabled={!stagedFile || importMutation.isPending} onClick={() => stagedFile && importMutation.mutate(stagedFile)}>{importMutation.isPending ? <><RefreshCw className="animate-spin" />导入中…</> : '开始导入'}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
