package image

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"

	"github.com/royalrick/anbanwriter/app/config"
)

func TestMapToDALLESize(t *testing.T) {
	tests := []struct {
		name  string
		size  string
		model string
		want  string
	}{
		// Empty defaults to 1024x1024
		{"empty defaults to 1024x1024", "", "dall-e-3", "1024x1024"},
		// Aspect ratio mapping for DALL-E 3
		{"16:9 maps to 1792x1024", "16:9", "dall-e-3", "1792x1024"},
		{"9:16 maps to 1024x1792", "9:16", "dall-e-3", "1024x1792"},
		{"1:1 maps to 1024x1024", "1:1", "dall-e-3", "1024x1024"},
		{"4:3 maps to 1792x1024", "4:3", "dall-e-3", "1792x1024"},
		{"3:4 maps to 1024x1792", "3:4", "dall-e-3", "1024x1792"},
		{"3:2 maps to 1792x1024", "3:2", "dall-e-3", "1792x1024"},
		{"2:3 maps to 1024x1792", "2:3", "dall-e-3", "1024x1792"},
		{"21:9 maps to 1792x1024", "21:9", "dall-e-3", "1792x1024"},
		// Tier suffix stripped before ratio lookup
		{"16:9:2K maps to 1792x1024", "16:9:2K", "dall-e-3", "1792x1024"},
		{"3:4:1K maps to 1024x1792", "3:4:1K", "dall-e-3", "1024x1792"},
		// DALL-E 2 always returns 1024x1024
		{"dall-e-2 any size defaults to 1024x1024", "16:9", "dall-e-2", "1024x1024"},
		{"dall-e-2 pixel format defaults to 1024x1024", "2560x1440", "dall-e-2", "1024x1024"},
		// GPT image models use a different OpenAI size set.
		{"gpt-image-1 16:9 maps to 1536x1024", "16:9", "gpt-image-1", "1536x1024"},
		{"gpt-image-1 3:4 maps to 1024x1536", "3:4", "gpt-image-1", "1024x1536"},
		{"gpt-image-1 1:1 maps to 1024x1024", "1:1", "gpt-image-1", "1024x1024"},
		// Pixel format not supported, defaults to 1024x1024
		{"pixel format not supported", "2560x1440", "dall-e-3", "1024x1024"},
		// Unknown format defaults to 1024x1024
		{"unknown format defaults", "badformat", "dall-e-3", "1024x1024"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := mapToDALLESize(tt.size, tt.model)
			if got != tt.want {
				t.Errorf("mapToDALLESize(%q, %q) = %q, want %q", tt.size, tt.model, got, tt.want)
			}
		})
	}
}

func TestOpenAIGenerateClassifiesHTMLResponseAsEndpointProtocolError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("<html><body>login required</body></html>"))
	}))
	defer srv.Close()

	provider, err := NewOpenAIProvider(&config.ImageAPI{
		Key:      "test-key",
		BaseURL:  srv.URL,
		Provider: "openai",
		Model:    "dall-e-3",
	})
	if err != nil {
		t.Fatalf("NewOpenAIProvider: %v", err)
	}

	_, err = provider.Generate(context.Background(), "a cat", nil)
	if err == nil {
		t.Fatal("expected error, got nil")
	}

	var genErr *GenerateError
	if !errors.As(err, &genErr) {
		t.Fatalf("error type = %T, want *GenerateError", err)
	}
	if genErr.Code != "endpoint_protocol" {
		t.Fatalf("Code = %q, want endpoint_protocol; error=%v", genErr.Code, err)
	}
	if !strings.Contains(genErr.Message, "OpenAI Images API") {
		t.Fatalf("Message = %q, want OpenAI Images API hint", genErr.Message)
	}
}

func TestOpenAIGenerateSavesBase64Image(t *testing.T) {
	pngData := []byte{
		0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
		0x00, 0x00, 0x00, 0x0D,
	}
	b64 := base64.StdEncoding.EncodeToString(pngData)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if body["response_format"] != "b64_json" {
			t.Fatalf("response_format = %v, want b64_json", body["response_format"])
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"created":1777599787,"data":[{"b64_json":"` + b64 + `"}]}`))
	}))
	defer srv.Close()

	provider, err := NewOpenAIProvider(&config.ImageAPI{
		Key:      "test-key",
		BaseURL:  srv.URL,
		Provider: "openai",
		Model:    "dall-e-3",
	})
	if err != nil {
		t.Fatalf("NewOpenAIProvider: %v", err)
	}

	result, err := provider.Generate(context.Background(), "a cat", nil)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if result.URL == "" {
		t.Fatal("result.URL is empty")
	}
	defer os.Remove(result.URL)

	got, err := os.ReadFile(result.URL)
	if err != nil {
		t.Fatalf("read generated temp file: %v", err)
	}
	if string(got) != string(pngData) {
		t.Fatalf("generated bytes = %v, want %v", got, pngData)
	}
}

func TestOpenAIGenerateUsesGPTImageBase64Defaults(t *testing.T) {
	pngData := []byte{0x89, 0x50, 0x4E, 0x47}
	b64 := base64.StdEncoding.EncodeToString(pngData)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		if _, ok := body["response_format"]; ok {
			t.Fatalf("response_format present for GPT image model: %v", body["response_format"])
		}
		if body["size"] != "1536x1024" {
			t.Fatalf("size = %v, want 1536x1024", body["size"])
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"created":1777599787,"data":[{"b64_json":"` + b64 + `"}]}`))
	}))
	defer srv.Close()

	provider, err := NewOpenAIProvider(&config.ImageAPI{
		Key:      "test-key",
		BaseURL:  srv.URL,
		Provider: "openai",
		Model:    "gpt-image-1",
		Size:     "16:9",
	})
	if err != nil {
		t.Fatalf("NewOpenAIProvider: %v", err)
	}

	result, err := provider.Generate(context.Background(), "a cat", nil)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	defer os.Remove(result.URL)
	got, err := os.ReadFile(result.URL)
	if err != nil {
		t.Fatalf("read generated temp file: %v", err)
	}
	if string(got) != string(pngData) {
		t.Fatalf("generated bytes = %v, want %v", got, pngData)
	}
}

func TestOpenAIGenerateRejectsURLOnlyResult(t *testing.T) {
	imageURL := "https://example.com/generated.png"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"created":1777599787,"data":[{"url":"` + imageURL + `"}]}`))
	}))
	defer srv.Close()

	provider, err := NewOpenAIProvider(&config.ImageAPI{
		Key:      "test-key",
		BaseURL:  srv.URL,
		Provider: "openai",
		Model:    "dall-e-3",
	})
	if err != nil {
		t.Fatalf("NewOpenAIProvider: %v", err)
	}

	_, err = provider.Generate(context.Background(), "a cat", nil)
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	var genErr *GenerateError
	if !errors.As(err, &genErr) {
		t.Fatalf("error type = %T, want *GenerateError", err)
	}
	if genErr.Code != "url_response_unsupported" {
		t.Fatalf("Code = %q, want url_response_unsupported", genErr.Code)
	}
}

func TestOpenAIGenerateReturnsErrorForEmptyImagePayload(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"created":1777599787,"data":[{}]}`))
	}))
	defer srv.Close()

	provider, err := NewOpenAIProvider(&config.ImageAPI{
		Key:      "test-key",
		BaseURL:  srv.URL,
		Provider: "openai",
		Model:    "dall-e-3",
	})
	if err != nil {
		t.Fatalf("NewOpenAIProvider: %v", err)
	}

	_, err = provider.Generate(context.Background(), "a cat", nil)
	if err == nil {
		t.Fatal("expected error, got nil")
	}

	var genErr *GenerateError
	if !errors.As(err, &genErr) {
		t.Fatalf("error type = %T, want *GenerateError", err)
	}
	if genErr.Code != "no_image" {
		t.Fatalf("Code = %q, want no_image", genErr.Code)
	}
}
