package agent

import "github.com/anbanai/anban-creator/server/model"

// Keep this list aligned with the authentication, provider-routing, and model
// inputs recognized by the pinned Claude Agent SDK 0.3.220. Profile keys are
// added separately and injected only from the frozen execution snapshot.
var claudeConflictingInheritedEnvKeys = []string{
	"AGENT_PROXY_AUTH_TOKEN",
	"AGENT_PROXY_URL",
	"ANTHROPIC_API_KEY",
	"ANTHROPIC_AWS_API_KEY",
	"ANTHROPIC_AWS_BASE_URL",
	"ANTHROPIC_AWS_WORKSPACE_ID",
	"ANTHROPIC_BEDROCK_BASE_URL",
	"ANTHROPIC_BEDROCK_MANTLE_BASE_URL",
	"ANTHROPIC_BEDROCK_SERVICE_TIER",
	"ANTHROPIC_CONFIG_DIR",
	"ANTHROPIC_CUSTOM_HEADERS",
	"ANTHROPIC_DEFAULT_FABLE_MODEL_DESCRIPTION",
	"ANTHROPIC_DEFAULT_FABLE_MODEL_NAME",
	"ANTHROPIC_DEFAULT_FABLE_MODEL_SUPPORTED_CAPABILITIES",
	"ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION",
	"ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME",
	"ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES",
	"ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION",
	"ANTHROPIC_DEFAULT_OPUS_MODEL_NAME",
	"ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES",
	"ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION",
	"ANTHROPIC_DEFAULT_SONNET_MODEL_NAME",
	"ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES",
	"ANTHROPIC_FEDERATION_RULE_ID",
	"ANTHROPIC_FOUNDRY_API_KEY",
	"ANTHROPIC_FOUNDRY_AUTH_TOKEN",
	"ANTHROPIC_FOUNDRY_BASE_URL",
	"ANTHROPIC_FOUNDRY_RESOURCE",
	"ANTHROPIC_GOOGLE_CLOUD_BASE_URL",
	"ANTHROPIC_GOOGLE_CLOUD_LOCATION",
	"ANTHROPIC_GOOGLE_CLOUD_PROJECT",
	"ANTHROPIC_GOOGLE_CLOUD_WORKSPACE_ID",
	"ANTHROPIC_IDENTITY_TOKEN",
	"ANTHROPIC_IDENTITY_TOKEN_FILE",
	"ANTHROPIC_ORGANIZATION_ID",
	"ANTHROPIC_PROFILE",
	"ANTHROPIC_SCOPE",
	"ANTHROPIC_SERVICE_ACCOUNT_ID",
	"ANTHROPIC_SMALL_FAST_MODEL",
	"ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION",
	"ANTHROPIC_UNIX_SOCKET",
	"ANTHROPIC_VERTEX_BASE_URL",
	"ANTHROPIC_VERTEX_PROJECT_ID",
	"ANTHROPIC_WORKSPACE_ID",
	"AWS_ACCESS_KEY_ID",
	"AWS_BEARER_TOKEN_BEDROCK",
	"AWS_CONFIG_FILE",
	"AWS_CONTAINER_AUTHORIZATION_TOKEN",
	"AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE",
	"AWS_CONTAINER_CREDENTIALS_FULL_URI",
	"AWS_CONTAINER_CREDENTIALS_RELATIVE_URI",
	"AWS_DEFAULT_REGION",
	"AWS_EC2_METADATA_SERVICE_ENDPOINT",
	"AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE",
	"AWS_PROFILE",
	"AWS_REGION",
	"AWS_ROLE_ARN",
	"AWS_SECRET_ACCESS_KEY",
	"AWS_SESSION_TOKEN",
	"AWS_SHARED_CREDENTIALS_FILE",
	"AWS_WEB_IDENTITY_TOKEN_FILE",
	"CLAUDE_CODE_3P_PROBE_WROTE_OPUS_DEFAULT",
	"CLAUDE_CODE_3P_PROBE_WROTE_SONNET_DEFAULT",
	"CLAUDE_CODE_ACCOUNT_TAGGED_ID",
	"CLAUDE_CODE_ACCOUNT_UUID",
	"CLAUDE_CODE_API_BASE_URL",
	"CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR",
	"CLAUDE_CODE_ARTIFACTS_API_BASE_URL",
	"CLAUDE_CODE_ASSUME_FIRST_PARTY_BASE_URL",
	"CLAUDE_CODE_CERT_STORE",
	"CLAUDE_CODE_CLIENT_CERT",
	"CLAUDE_CODE_CLIENT_KEY",
	"CLAUDE_CODE_CLIENT_KEY_PASSPHRASE",
	"CLAUDE_CODE_CUSTOM_OAUTH_URL",
	"CLAUDE_CODE_DESIGN_OAUTH_CLIENT_ID",
	"CLAUDE_CODE_ENABLE_PROXY_AUTH_HELPER",
	"CLAUDE_CODE_HFI_BEARER_TOKEN",
	"CLAUDE_CODE_HOST_AUTH_ENV_VAR",
	"CLAUDE_CODE_HOST_AUTH_REFRESH_TIMEOUT_MS",
	"CLAUDE_CODE_HOST_CREDS_FILE",
	"CLAUDE_CODE_MOCK_REMOTE_SETTINGS",
	"CLAUDE_CODE_OAUTH_CLIENT_ID",
	"CLAUDE_CODE_OAUTH_REFRESH_TOKEN",
	"CLAUDE_CODE_OAUTH_SCOPES",
	"CLAUDE_CODE_OAUTH_TOKEN",
	"CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR",
	"CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST",
	"CLAUDE_CODE_PROXY_AUTH_HELPER_TTL_MS",
	"CLAUDE_CODE_PROXY_RESOLVES_HOSTS",
	"CLAUDE_CODE_REMOTE_SETTINGS_PATH",
	"CLAUDE_CODE_REMOTE_SETTINGS_POLL_MS",
	"CLAUDE_CODE_SDK_HAS_HOST_AUTH_REFRESH",
	"CLAUDE_CODE_SDK_HAS_OAUTH_REFRESH",
	"CLAUDE_CODE_SESSION_ACCESS_TOKEN",
	"CLAUDE_CODE_SKIP_ANTHROPIC_AWS_AUTH",
	"CLAUDE_CODE_SKIP_ANTHROPIC_GOOGLE_CLOUD_AUTH",
	"CLAUDE_CODE_SKIP_AWS_CRED_CACHE",
	"CLAUDE_CODE_SKIP_BEDROCK_AUTH",
	"CLAUDE_CODE_SKIP_FOUNDRY_AUTH",
	"CLAUDE_CODE_SKIP_MANTLE_AUTH",
	"CLAUDE_CODE_SKIP_VERTEX_AUTH",
	"CLAUDE_CODE_USE_ANTHROPIC_AWS",
	"CLAUDE_CODE_USE_ANTHROPIC_GOOGLE_CLOUD",
	"CLAUDE_CODE_USE_BEDROCK",
	"CLAUDE_CODE_USE_FOUNDRY",
	"CLAUDE_CODE_USE_GATEWAY",
	"CLAUDE_CODE_USE_MANTLE",
	"CLAUDE_CODE_USE_VERTEX",
	"CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR",
	"CLAUDE_CONFIG_DIR",
	"CLAUDE_LOCAL_OAUTH_API_BASE",
	"CLAUDE_LOCAL_OAUTH_APPS_BASE",
	"CLAUDE_LOCAL_OAUTH_CONSOLE_BASE",
	"CLAUDE_SESSION_INGRESS_TOKEN_FILE",
	"CLAUDE_SECURESTORAGE_CONFIG_DIR",
	"CLAUDE_TRUSTED_DEVICE_TOKEN",
	"CLOUD_ML_REGION",
	"CLOUDSDK_AUTH_ACCESS_TOKEN",
	"ENVIRONMENT_SERVICE_KEY",
	"GCE_METADATA_HOST",
	"GCE_METADATA_IP",
	"GCLOUD_PROJECT",
	"GOOGLE_APPLICATION_CREDENTIALS",
	"GOOGLE_CLOUD_PROJECT",
	"GOOGLE_CLOUD_QUOTA_PROJECT",
	"METADATA_SERVER_DETECTION",
	"USE_LOCAL_OAUTH",
	"USE_STAGING_OAUTH",
	"_CLAUDE_CODE_ASSUME_FIRST_PARTY_BASE_URL",
}

// ClaudeRuntimeEnv returns an allowlisted copy of the Server-owned Claude
// configuration for delivery to a single authenticated Agent execution.
func ClaudeRuntimeEnv(configured map[string]string) map[string]string {
	keys := model.ClaudeProfileEnvKeys()
	result := make(map[string]string, len(keys))
	for _, key := range keys {
		if value, exists := configured[key]; exists {
			result[key] = value
		}
	}
	if len(result) == 0 {
		return nil
	}
	return result
}

// ClaudeRuntimeEnvKeys returns the stable injection order for the shared
// Server-to-Agent runtime contract.
func ClaudeRuntimeEnvKeys() []string {
	return model.ClaudeProfileEnvKeys()
}

// ClaudeEnvironmentKeysToUnset includes supported Profile keys and inherited
// authentication or provider-routing keys that must not influence a managed run.
func ClaudeEnvironmentKeysToUnset() []string {
	profileKeys := model.ClaudeProfileEnvKeys()
	result := make([]string, 0, len(profileKeys)+len(claudeConflictingInheritedEnvKeys))
	result = append(result, profileKeys...)
	result = append(result, claudeConflictingInheritedEnvKeys...)
	return result
}

func ValidateClaudeRuntimeEnv(runtimeEnv map[string]string) error {
	return model.ValidateClaudeProfileEnvs(runtimeEnv, true)
}
