import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { rangeForPreset, periodError, type AnalyticsPeriod } from '@/lib/analytics-period'
export default function AnalyticsPeriodControls({ value, onChange }: { value: AnalyticsPeriod; onChange: (value: AnalyticsPeriod) => void }) {
  return <section className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card px-3 py-2.5" aria-label="数据时间范围">
    <div className="space-y-1"><div className="flex flex-wrap gap-1" aria-label="日期范围">{([['7d', '近 7 天'], ['30d', '近 30 天'], ['week', '本周'], ['month', '本月'], ['custom', '自定义']] as const).map(([preset, label]) => <Button key={preset} size="sm" variant={value.preset === preset ? 'secondary' : 'ghost'} aria-pressed={value.preset === preset} onClick={() => onChange({ ...value, preset, ...(preset === 'custom' ? {} : rangeForPreset(preset)) })}>{label}</Button>)}</div><p className="text-xs text-muted-foreground">{value.from} 至 {value.to} · 北京时间</p></div>
    {value.preset === 'custom' && <div className="flex flex-wrap gap-2"><label className="grid gap-1 text-xs text-muted-foreground">开始日期<Input type="date" aria-label="开始日期" className="w-40" value={value.from} max={value.to} onChange={(e) => { if (e.target.value) onChange({ ...value, from: e.target.value }) }} /></label><label className="grid gap-1 text-xs text-muted-foreground">结束日期<Input type="date" aria-label="结束日期" className="w-40" value={value.to} min={value.from} onChange={(e) => { if (e.target.value) onChange({ ...value, to: e.target.value }) }} /></label>{periodError(value.from, value.to) && <p role="alert" className="text-xs text-destructive">{periodError(value.from, value.to)}</p>}</div>}
    <div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">趋势粒度</span><div className="flex rounded-lg bg-muted/50 p-0.5" aria-label="趋势粒度">{([['day', '按天'], ['week', '按周'], ['month', '按月']] as const).map(([granularity, label]) => <Button key={granularity} size="sm" variant={value.granularity === granularity ? 'secondary' : 'ghost'} aria-pressed={value.granularity === granularity} onClick={() => onChange({ ...value, granularity })}>{label}</Button>)}</div></div>
  </section>
}
