import { useId } from 'react'
import { BarChart3, Loader2 } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import type { AnalyticsPoint } from '@/lib/analytics-period'
interface Metric { key: string; label: string; color: string; summary?: boolean; format?: (value: number) => string }
export default function AnalyticsTrend({ title = '数据趋势', description, metrics, data, selectedMetric, onMetricChange, loading, emptyMessage = '当前时间范围暂无数据，请调整日期或导入数据。' }: { title?: string; description?: string; metrics: readonly Metric[]; data: AnalyticsPoint[]; selectedMetric: string; onMetricChange: (key: string) => void; loading?: boolean; emptyMessage?: string }) {
  const gradient = useId().replace(/:/g, '')
  const metric = metrics.find((item) => item.key === selectedMetric) ?? metrics[0]
  const format = metric.format ?? ((value: number) => value.toLocaleString('zh-CN'))
  const primaryMetrics = metrics.filter(item => item.summary !== false).slice(0, 4)
  const extraMetrics = metrics.filter(item => !primaryMetrics.includes(item))
  const hasData = data.some((point) => typeof point[metric.key] === 'number')
  return <Card><CardHeader className="gap-3"><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle>{title}</CardTitle><div className="flex flex-wrap gap-1" aria-label={`${title}指标`}>{primaryMetrics.map((item) => <Button key={item.key} size="sm" variant={selectedMetric === item.key ? 'secondary' : 'ghost'} aria-pressed={selectedMetric === item.key} onClick={() => onMetricChange(item.key)}><span className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} />{item.label}</Button>)}{extraMetrics.length > 0 && <select aria-label="更多趋势指标" className="h-8 max-w-40 rounded-md border bg-background px-2 text-xs" value={extraMetrics.some(item => item.key === selectedMetric) ? selectedMetric : ""} onChange={event => { if (event.target.value) onMetricChange(event.target.value) }}><option value="" disabled>更多指标</option>{extraMetrics.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select>}</div></div>{description && <p className="text-xs leading-relaxed text-muted-foreground">{description}</p>}</CardHeader><CardContent>
    {loading ? <div role="status" className="flex h-64 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />正在读取数据…</div> : hasData ? <><div className="h-72 min-w-0 sm:h-80" role="img" aria-label={`${title}：${metric.label}`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 12, right: 16, left: 0, bottom: 0 }}><defs><linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={metric.color} stopOpacity={0.14} /><stop offset="100%" stopColor={metric.color} stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" className="stroke-border" /><XAxis dataKey="date" tickFormatter={(value: string) => value.slice(5)} tickLine={false} axisLine={false} minTickGap={32} tick={{ fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} width={64} tick={{ fontSize: 11 }} tickFormatter={(value: number) => format(value)} /><Tooltip labelFormatter={(value) => String(value)} formatter={(value) => [value == null ? '—' : format(Number(value)), metric.label]} contentStyle={{ borderRadius: 8, borderColor: 'var(--border)', background: 'var(--card)', color: 'var(--foreground)' }} /><Area type="linear" dataKey={metric.key} stroke={metric.color} fill={`url(#${gradient})`} strokeWidth={2} dot={{ r: 3, fill: metric.color, strokeWidth: 0 }} activeDot={{ r: 5 }} connectNulls={false} isAnimationActive={false} /></AreaChart></ResponsiveContainer></div><details className="mt-3 text-xs text-muted-foreground"><summary className="cursor-pointer">查看趋势明细</summary><div className="mt-2 max-h-48 overflow-auto"><table className="w-full text-left"><thead><tr><th className="py-2">日期 / 周起始 / 月起始</th><th>{metric.label}</th></tr></thead><tbody>{data.map((point) => <tr key={point.date}><td className="py-1">{point.date}</td><td>{typeof point[metric.key] === 'number' ? format(point[metric.key] as number) : '—'}</td></tr>)}</tbody></table></div></details></> : <div className="flex h-64 flex-col items-center justify-center gap-3 text-sm text-muted-foreground"><BarChart3 className="h-8 w-8 opacity-40" /><p>{emptyMessage}</p></div>}
  </CardContent></Card>
}
